name: MINE 
channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - ffmpeg=4.3=hf484d3e_0
  - kornia=0.3.0=pyh9f0ad1d_0
  - pytorch=1.8.1=py3.8_cuda10.1_cudnn7.6.3_0
  - pyyaml=5.3.1=py38h7b6447c_1
  - scipy=1.6.2=py38h91f5cce_0
  - tensorboard=2.4.1=pyhd8ed1ab_0
  - tensorboard-plugin-wit=1.8.0=pyh44b312d_0
  - torchvision=0.9.1=py38_cu101
  - tqdm=4.60.0=pyhd8ed1ab_0
  - yaml=0.2.5=h7b6447c_0
  - pip:
    - lpips==0.1.3
    - opencv-python==4.5.1.48
